#!/bin/bash
# Demo script showing the new interactive planning workflow

echo "======================================================================="
echo "AGENT ORCHESTRATOR - Interactive Planning Demo"
echo "======================================================================="
echo ""
echo "This demo shows the new head node planning capability that allows you to:"
echo "  • Discuss and refine plans with Claude before execution"
echo "  • Visualize task dependencies and execution phases"
echo "  • Approve plans before launching any agents"
echo ""
echo "The workflow is:"
echo "  1. Submit a high-level goal to the planning head node"
echo "  2. Interactively refine the task breakdown"
echo "  3. Approve the plan"
echo "  4. Execute with multiple specialized agents"
echo ""
echo "======================================================================="
echo ""

# Example planning session
echo "📋 Example 1: Starting an interactive planning session"
echo "Command: ./orchestrate plan 'Build a REST API for user management'"
echo ""
echo "This will:"
echo "  - Start Claude as the planning head node"
echo "  - Show initial task decomposition"
echo "  - Let you discuss and refine the plan"
echo "  - Ask for approval before execution"
echo ""

echo "📋 Example 2: List and manage planning sessions"
echo "Command: ./orchestrate plan-list"
echo ""
echo "Shows all planning sessions with their status (planning/approved/executed)"
echo ""

echo "📋 Example 3: Execute an approved plan"
echo "Command: ./orchestrate execute-plan <session-id>"
echo ""
echo "This will:"
echo "  - Load the approved plan"
echo "  - Submit all tasks to the queue"
echo "  - Optionally start the orchestrator to process them"
echo ""

echo "======================================================================="
echo "Try it now with:"
echo ""
echo "  ./orchestrate plan 'Your project goal here'"
echo ""
echo "======================================================================="