version: 1
disable_existing_loggers: false

formatters:
  default:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: default
    stream: ext://sys.stdout
  
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: default
    filename: autodev.log

root:
  level: INFO
  handlers: [console, file]

loggers:
  autodev:
    level: DEBUG
    handlers: [console, file]
    propagate: false